version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./data:/app/data:rw
        ports:
            - '${PORT}:${PORT}'
#            - '5555:5555' todo: for prisma studio
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
            PGDATA: /data/postgres
        restart: always
        ports:
            - 127.0.0.1:${DATABASE_PORT}:5432
        volumes:
            - './data/postgres:/data/postgres'
    db_admin:
        image: dbeaver/cloudbeaver
        ports:
            - '${DB_ADMIN_PORT}:8978'
        volumes:
            - ./data:/opt/data:rw
            - ./data/db_admin:/opt/cloudbeaver/workspace
