version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./data.sqlite3:/app/data.sqlite3:rw
            - ./logs:/app/logs:rw
            - ./src/config/config.ts:/app/src/config/config.ts:ro
        ports:
            - "4000:4000"
