/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "accountSuspended": string;
        "unauthorized": string;
        "accountHasNoRole": string;
        "invalidPassword": string;
        "accountNotFound": string;
        "emailNotSent": string;
        "invalidCode": string;
        "tokenExpired": string;
    };
    "notifications": {
        "notifications": {
            "title": string;
            "description": string;
            "looking_for_pair": {
                "title": string;
            };
            "paired": {
                "title": string;
            };
            "gift_sent": {
                "title": string;
            };
            "gift_received": {
                "title": string;
            };
            "gift_not_received": {
                "title": string;
            };
        };
        "notifications_not_found": {
            "title": string;
            "description": string;
        };
        "new_message": {
            "title": string;
            "link": string;
        };
    };
    "translations": {
        "hello": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
